env:
   global:
     - CONAN_REFERENCE: "Boost.Build/1.64.0"
     - CONAN_CHANNEL: "ci"
     - CONAN_STABLE_BRANCH_PATTERN: "release/*"
     - CONAN_TOTAL_PAGES: 1

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - conan create $CONAN_REFERENCE
  