env:
   global:
     - CONAN_REFERENCE: "Boost.Build/1.64.0"
     - CONAN_SUBJECT: "bincrafters"
     - CONAN_CHANNEL: "ci"

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh
  
script:
  - export CONAN_REFERENCE_FULL=${CONAN_REFERENCE}@${CONAN_SUBJECT}/${CONAN_CHANNEL}
  - echo ${CONAN_REFERENCE_FULL}
  - conan create ${CONAN_REFERENCE_FULL}
  - conan user -p ${CONAN_KEY} --remote ${CONAN_SUBJECT} -c ${CONAN_USER}
  - conan remote add bincrafters "https://api.bintray.com/conan/bincrafters/public-conan"
  - conan remote add_ref ${CONAN_REFERENCE_FULL}
  - conan upload ${CONAN_REFERENCE_FULL}
